language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - hhvm-3.3
  - hhvm-3.6
  - hhvm-3.9
  - hhvm-3.12
  - hhvm-3.15
  - hhvm-3.1

before_script:
  - touch /tmp/oodb.db
  - mysql -e 'create database oodb;'
  - psql template1 -c 'CREATE EXTENSION "uuid-ossp";' -U postgres
  - psql -c 'create database oodb;' -U postgres
  - php replica2.php onlyphp
  - cp rb.php testing/cli/testcontainer/rb.php  
  - cd testing/cli
    
 
script: php runtests.php
